In [1]:
import numpy as np

In [8]:
foo = np.array([
    [1, 5, 3],
    [3, 5, 6],
    [7, 3, 9]
])

In [10]:
foo == 3

array([[False, False,  True],
       [ True, False, False],
       [False,  True, False]])

In [11]:
mask = foo == 3

In [12]:
foo[mask]

array([3, 3, 3])

In [15]:
foo[mask] = 0
foo

array([[1, 5, 0],
       [0, 5, 6],
       [7, 0, 9]])

Only first and third row

In [16]:
foo[[True, False, True]]

array([[1, 5, 0],
       [7, 0, 9]])

Only first and third column

In [17]:
foo[:, [True, False, True]]

array([[1, 0],
       [0, 6],
       [7, 9]])

In [18]:
foo[[True, False, True], [True, False, True]]

array([1, 9])

Now the output isn't something we anticipated. We were prepared to see `[[1, 0], [7, 9]]`.
That's because numpy treats that kind of indexing just like slicing and the output is the same as when we would call
`foo[[0, 2], [0, 2]]`. That returns only two values from `[0, 0]` and `[2, 2]` positions