In [1]:
import numpy as np

Because of random number generators changing across the versions of numpy it is recommended to use generator.

In [2]:
generator = np.random.default_rng(seed=123)

In [3]:
generator.integers(low=1, high=7, size=3)

array([1, 5, 4])

In [4]:
generator.choice(a=10, size=3, replace=True)

array([0, 9, 2])

In [5]:
generator.permutation([[1, 2], [3, 4], [5, 6], [7, 8]], axis=0)

array([[5, 6],
       [1, 2],
       [7, 8],
       [3, 4]])

In [6]:
generator.permutation([[1, 2], [3, 4], [5, 6], [7, 8]], axis=1)

array([[2, 1],
       [4, 3],
       [6, 5],
       [8, 7]])