In [3]:
import numpy as np

In [6]:
foo = np.array([
    [2, 3, 1],
    [1, 0, 3]
])

boo = np.array([3, 4, 5])

In [7]:
boo+foo

array([[5, 7, 6],
       [4, 4, 8]])

### Broadcasting rules
* We check if dimensions of arrays are compatible
* Dimension is compatible if their value is equal, or it's 1
* If all dimensions are compatible that means the arrays are also compatible
In above example `boo` array is extended like that
```python
boo = [
        [3, 4, 5],
        [3, 4, 5]
]
```
That makes carrying out addition possible

In [8]:
a = np.random.randint(low=0, high=10, size=(1, 5))
b = np.random.randint(low=0, high=10, size=(5, 1))
a+b

array([[ 2, 11, 10, 10,  7],
       [ 8, 17, 16, 16, 13],
       [ 0,  9,  8,  8,  5],
       [ 6, 15, 14, 14, 11],
       [ 7, 16, 15, 15, 12]], dtype=int32)

In [10]:
a = np.random.randint(low=0, high=10, size=(2, 5))
b = np.random.randint(low=0, high=10, size=(4, 1))
a+b

ValueError: operands could not be broadcast together with shapes (2,5) (4,1) 

The error showed up because there is no easy way to expand first dimension of first array even tho it would only need to be duplicated. The second dimension is compatible

In [14]:
a = np.random.randint(low=0, high=10, size=(2, 5, 5))
b = np.random.randint(low=0, high=10, size=5)
a+b

array([[[ 1, 11, 10,  1,  5],
        [ 9, 12,  7,  3,  7],
        [ 6, 13, 14,  8,  3],
        [10, 13, 15,  8, 12],
        [ 9, 15, 11,  9, 11]],

       [[ 4, 14, 15,  7, 12],
        [ 5, 10, 15,  2,  7],
        [ 8, 11, 12,  4, 10],
        [10, 14, 10,  5,  5],
        [10, 13,  7,  7,  3]]], dtype=int32)

Even if we don't define all dimensions, the numpy will interpret size of `b` as `(1, 1, 5)` and from here we can see, that `a` and `b` are once again compatible