In [1]:
import numpy as np

In [34]:
foo = np.arange(start=0, stop=9)
foo

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
np.reshape(foo, newshape=(3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
np.reshape(foo, newshape=(1, 9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [31]:
np.reshape(foo, newshape=(9, 1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [32]:
np.reshape(foo, newshape=(2, 5))

ValueError: cannot reshape array of size 9 into shape (2,5)

In [25]:
foo.reshape(3, 3)
foo

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

reshape() returns new array, the original stays the same

In [42]:
foo.shape = (3,3)
foo

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

To change shape of array we can simpy modify it's `shape` attribute

In [36]:
bar = np.arange(start=0, stop=8)
hoo = bar.reshape(2, 4)
hoo

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Order `C` and `F`

In [37]:
hoo.reshape(4, 2, order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [38]:
hoo.reshape(4, 2, order='F')

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In [39]:
hoo.reshape(2, 2, 2, order='C')

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
hoo.reshape(2, 2, 2, order='F')

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [41]:
bar.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Transposition

In [52]:
zoo = np.arange(start=0, stop=8)
zoo.shape=(4,2)
zoo

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [53]:
zoo.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [54]:
np.transpose(zoo)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])