In [12]:
import numpy as np

## Randint

In [26]:
np.random.randint(low=0, high=10, size=3)

array([4, 6, 9], dtype=int32)

In [27]:
np.random.seed(42)
np.random.randint(low=0, high=10, size=3)

array([6, 3, 7], dtype=int32)

The results before setting `seed` are not reproducible

## Choice

In [46]:
np.random.seed(45)
np.random.choice(
    a=np.arange(1, 7),
    size=5,
    replace=True,
    p=None
)

array([4, 4, 5, 1, 6])

In [47]:
np.random.choice(
    a=np.arange(1, 7),
    size=5,
    replace=False,
    p=None
)

array([3, 5, 2, 1, 4])

In [49]:
np.random.choice(
    a=np.arange(1, 7),
    size=5,
    replace=True,
    p=np.array([1, 0, 0, 0, 0, 0])
)

array([1, 1, 1, 1, 1])

## Permutation

In [50]:
foo = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

np.random.permutation(foo)

array([[7, 8],
       [3, 4],
       [1, 2],
       [5, 6]])

## Uniform

In [57]:
np.random.uniform(low=1.0, high=2.0, size=(3, 3))

array([[1.04603804, 1.3986565 , 1.1337718 ],
       [1.3046713 , 1.76641841, 1.83608144],
       [1.96624161, 1.7680354 , 1.75521219]])

In [58]:
foo = np.random.uniform(low=1.0, high=2.0, size=(10, 10))
foo.mean()

np.float64(1.5152204273611543)

## Normal

In [60]:
np.random.normal(loc = 0.0, scale = 1.0, size = 5)

array([ 0.0219286 , -0.26627554, -0.11275395, -0.59073531, -0.32586725])

## Binomial

In [61]:
np.random.binomial(n=10, p=0.75, size = (3, 2))

array([[ 7,  7],
       [ 9,  9],
       [10,  5]], dtype=int32)