In [1]:
import numpy as np

In [3]:
np.array([np.inf, -np.inf])

array([ inf, -inf])

In [4]:
np.array([1, -1])/0

C:\Users\mateu\AppData\Local\Temp\ipykernel_9304\4162858187.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([1, -1])/0


array([ inf, -inf])

In [5]:
np.inf * 42

inf

In [6]:
np.inf + np.inf

inf

In [7]:
np.inf - np.inf

nan

In [8]:
-np.inf * -1

inf

In [9]:
np.inf/np.inf

nan

In [10]:
np.inf == np.inf

True

In [11]:
foo = np.array([1., 2., np.inf, 3., -np.inf])

In [14]:
[foo==np.inf]

[array([False, False,  True, False, False])]

In [15]:
np.isposinf(foo)

array([False, False,  True, False, False])

In [16]:
np.isneginf(foo)

array([False, False, False, False,  True])

In [17]:
np.isinf(foo)

array([False, False,  True, False,  True])