In [1]:
import numpy as np
from tensorflow.compiler.tf2xla.python.xla import set_dynamic_dimension_size

In [2]:
generator = np.random.default_rng(seed=2121)

In [13]:
foo = generator.integers(low=0, high=11, size=2*10**6)
foo[:10]

array([ 2,  2,  6,  6,  6,  0,  2, 10,  0,  8])

In [12]:
boo = generator.integers(low=0, high=11, size=2*10**6)
boo[:10]

array([ 5,  4,  6,  1,  8, 10,  6,  7,  6,  0])

Generating new array in which every `zoo[i]` is either `boo[i]*2` or `boo[i]/2` depending on corresponding element of `foo` being even or not

In [11]:
zoo = np.where(foo % 2 == 0, boo*2, boo/2)
zoo[:10]

array([ 3. ,  1. , 10. ,  8. ,  1.5,  2. ,  6. ,  2. ,  4. , 10. ])