In [1]:
import numpy as np

In [2]:
foo = np.array([
    [1, np.nan],
    [np.nan, np.nan],
    [2, 1],
    [np.nan, 8]
])

In [5]:
np.isnan(foo)

array([[False,  True],
       [ True,  True],
       [False, False],
       [ True, False]])

In [9]:
np.any(np.isnan(foo), axis=1)

array([ True,  True, False,  True])

In [10]:
np.all(np.isnan(foo), axis=1)

array([False,  True, False, False])