## Setup

After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner. You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location

In [1]:
import numpy as np

In [3]:
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7, 7))
print(gold)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [5]:
locations = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])
print(locations)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


## Solution

In [8]:
np.array([gold[i,j] for i,j in locations])


[2 6 2 8 2]


In [9]:
np.array(gold[locations[:,0], locations[:,1]])

array([2, 6, 2, 8, 2], dtype=int32)