## Setup

### With your high school reunion fast approaching, you decide to get in shape and lose some weight. You record your weight every day for 5 weeks starting on Monday. Given  these daily weights, build an array with your average weight per weekend.

In [1]:
import numpy as np

In [10]:
dailywts = 185 - np.arange(5*7)/5

In [11]:
print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


## Solution

In [16]:
avgs = (dailywts[5::7] + dailywts[6::7])/2
print(avgs)

[183.9 182.5 181.1 179.7 178.3]


### Possible solution for calculating average for whole weekend

In [17]:
avgs = np.array([np.mean(dailywts[0+i*7:7+i*7]) for i in range(dailywts.size//7)])
print(avgs)

[184.4 183.  181.6 180.2 178.8]


In [18]:
weekly_weights = dailywts.reshape(5, 7)
weekly_avg = weekly_weights.mean(axis=1)
print(weekly_avg)

[184.4 183.  181.6 180.2 178.8]
