In [30]:
import numpy as np

### Basic properties

In [31]:
arr = np.array([1, 2, 3, 4, 5])

print(f'arr: {arr}')
print(f'arr.ndim: {arr.ndim}')
print(f'arr.shape: {arr.shape}')
print(f'len(arr): {len(arr)}')
print(f'arr.size: {arr.size}')
print(f'type(arr): {type(arr)}')

arr: [1 2 3 4 5]
arr.ndim: 1
arr.shape: (5,)
len(arr): 5
arr.size: 5
type(arr): <class 'numpy.ndarray'>


In [32]:
arr_2d = np.array([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])

print(f'arr_2d: {arr_2d}')
print(f'arr_2d.ndim: {arr_2d.ndim}')
print(f'arr_2d.shape: {arr_2d.shape}')
print(f'len(arr_2d): {len(arr_2d)}')
print(f'arr_2d.size: {arr_2d.size}')

arr_2d: [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
arr_2d.ndim: 2
arr_2d.shape: (3, 5)
len(arr_2d): 3
arr_2d.size: 15


### Types of data

In [33]:
np.array([
    [1, 2, 3],
    [1.5, 1.3, 1.6],
])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


Arrays can be only of one type - first list of ints is converted to floats

In [34]:
arr = np.array([1, 'hello', 3])
print(arr)
print(arr.dtype)

['1' 'hello' '3']
<U21


Here integers are casted to strings of size less than 21 characters

In [35]:
arr[0] = 'very very very very very long string'
print(arr)

['very very very very v' 'hello' '3']


Assigned value is shorten