In [2]:
import numpy as np

### By numpy.array

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
np.array([
    [1, 2],
    [1, 2]
])

array([[1, 2],
       [1, 2]])

In [5]:
np.array([
    [
        [1, 2], [1, 2]
    ],
    [
        [1, 2], [1, 2]
    ]
])

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

### By numpy.zeros

In [6]:
np.zeros(shape=5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros(shape=(2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.zeros(shape=5, dtype='int')

array([0, 0, 0, 0, 0])

In [9]:
np.zeros(shape=5, dtype='str')

array(['', '', '', '', ''], dtype='<U1')

### By numpy.full

In [10]:
np.full(shape=5, fill_value=15, dtype=float)

array([15., 15., 15., 15., 15.])

### By numpy.arange

In [11]:
np.arange(start=1, stop=16, step=5)

array([ 1,  6, 11])

Start is inclusive and stop is not

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### By numpy.random.randint

In [22]:
np.random.randint(low=5, high=10, size=(3,4))

array([[6, 6, 8, 8],
       [5, 5, 6, 9],
       [7, 5, 9, 5]], dtype=int32)