In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

### Accessing element

In [8]:
arr[0]

np.int64(1)

In [9]:
arr[-1]

np.int64(5)

In [10]:
arr[15]

IndexError: index 15 is out of bounds for axis 0 with size 5

In [11]:
arr[[0, 3]]

array([1, 4])

In [12]:
arr[[0,1,1,1]]

array([1, 2, 2, 2])

### Slicing

In [14]:
arr[0:2]

array([1, 2])

In [15]:
arr[:2]

array([1, 2])

In [16]:
arr[:-1]

array([1, 2, 3, 4])

In [18]:
arr[::2]

array([1, 3, 5])

In [17]:
arr[:-1:2]

array([1, 3])

In [21]:
arr[:5]

array([1, 2, 3, 4, 5])

In [26]:
arr[1:1]

array([], dtype=int64)

In [25]:
arr[1:2]

array([2])

In [27]:
arr[:10]

array([1, 2, 3, 4, 5])

arr[start:stop:step] - inclusive start, exclusive stop, stop can be out of bounds

### Modifying multiple elements

In [29]:
arr[[0, 2, 4]] = [15, 20, 7]
print(arr)

[15  2 20  4  7]


In [30]:
arr[[0, 2, 4]] = 0
print(arr)

[0 2 0 4 0]
