In [1]:
import numpy as np

In [2]:
arr = np.array([
    [[ 1,  2,  3], [ 4,  5,  6], [ 7,  8,  9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

In [18]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr[0,0]

array([1, 2, 3])

In [20]:
arr[0,0,0]

np.int64(1)

In [21]:
arr[0,:,0]

array([1, 4, 7])

In [22]:
arr[::2,::2,::2]

array([[[ 1,  3],
        [ 7,  9]],

       [[19, 21],
        [25, 27]]])

In [24]:
arr[[0,1,2], [0,1,2], [0,1,2]]

array([ 1, 14, 27])