In [7]:
import numpy as np

In [8]:
foo = np.array([[1, 2], [1, 1]])
zoo = np.array([[4, 2], [0, 1]])

In [9]:
foo + zoo

array([[5, 4],
       [1, 2]])

In [10]:
foo - zoo

array([[-3,  0],
       [ 1,  0]])

Element wise multiplication

In [11]:
foo * zoo

array([[4, 4],
       [0, 1]])

Matrix multiplication

In [12]:
foo @ zoo

array([[4, 4],
       [4, 3]])

Adding scaler

In [13]:
foo + np.full_like(foo, 5)

array([[6, 7],
       [6, 6]])

In [14]:
foo + 5

array([[6, 7],
       [6, 6]])